//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVideos.OnlineVideosWebservice
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Name = "ReportType", Namespace = "http://tempuri.org/")]
    public enum ReportType : int
    {

        [EnumMember()]
        Suggestion = 0,

        [EnumMember()]
        Broken = 1,

        [EnumMember()]
        ConfirmedBroken = 2,

        [EnumMember()]
        RejectedBroken = 3,

        [EnumMember()]
        Fixed = 4,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Name = "Report", Namespace = "http://tempuri.org/")]
    public partial class Report : object
    {

        private string Site_FKField;

        private System.DateTime DateField;

        private string MessageField;

        private ReportType TypeField;

        private Site SiteField;

        [DataMember(EmitDefaultValue = false)]
        public string Site_FK
        {
            get
            {
                return this.Site_FKField;
            }
            set
            {
                this.Site_FKField = value;
            }
        }

        [DataMember(IsRequired = true, Order = 1)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [DataMember(IsRequired = true, Order = 3)]
        public ReportType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 4)]
        public Site Site
        {
            get
            {
                return this.SiteField;
            }
            set
            {
                this.SiteField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Name = "Site", Namespace = "http://tempuri.org/")]
    public partial class Site : object
    {

        private string XMLField;

        private SiteState StateField;

        private string NameField;

        private string Owner_FKField;

        private System.DateTime LastUpdatedField;

        private string LanguageField;

        private string DescriptionField;

        private bool IsAdultField;

        private string RequiredDllField;

        private User OwnerField;

        private Dll DllField;

        private uint ReportCountField;

        [DataMember(EmitDefaultValue = false)]
        public string XML
        {
            get
            {
                return this.XMLField;
            }
            set
            {
                this.XMLField = value;
            }
        }

        [DataMember(IsRequired = true, Order = 1)]
        public SiteState State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 3)]
        public string Owner_FK
        {
            get
            {
                return this.Owner_FKField;
            }
            set
            {
                this.Owner_FKField = value;
            }
        }

        [DataMember(IsRequired = true, Order = 4)]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 5)]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 6)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [DataMember(IsRequired = true, Order = 7)]
        public bool IsAdult
        {
            get
            {
                return this.IsAdultField;
            }
            set
            {
                this.IsAdultField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 8)]
        public string RequiredDll
        {
            get
            {
                return this.RequiredDllField;
            }
            set
            {
                this.RequiredDllField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 9)]
        public User Owner
        {
            get
            {
                return this.OwnerField;
            }
            set
            {
                this.OwnerField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 10)]
        public Dll Dll
        {
            get
            {
                return this.DllField;
            }
            set
            {
                this.DllField = value;
            }
        }

        [DataMember(IsRequired = true, Order = 11)]
        public uint ReportCount
        {
            get
            {
                return this.ReportCountField;
            }
            set
            {
                this.ReportCountField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Name = "User", Namespace = "http://tempuri.org/")]
    public partial class User : object
    {

        private string EmailField;

        private string PasswordField;

        private bool IsAdminField;

        private Site[] SitesField;

        private Dll[] DllsField;

        [DataMember(EmitDefaultValue = false)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [DataMember(EmitDefaultValue = false)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [DataMember(IsRequired = true, Order = 2)]
        public bool IsAdmin
        {
            get
            {
                return this.IsAdminField;
            }
            set
            {
                this.IsAdminField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 3)]
        public Site[] Sites
        {
            get
            {
                return this.SitesField;
            }
            set
            {
                this.SitesField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 4)]
        public Dll[] Dlls
        {
            get
            {
                return this.DllsField;
            }
            set
            {
                this.DllsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Name = "Dll", Namespace = "http://tempuri.org/")]
    public partial class Dll : object
    {

        private string NameField;

        private System.DateTime LastUpdatedField;

        private string Owner_FKField;

        private string MD5Field;

        private Site[] SitesField;

        private User OwnerField;

        [DataMember(EmitDefaultValue = false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [DataMember(IsRequired = true, Order = 1)]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string Owner_FK
        {
            get
            {
                return this.Owner_FKField;
            }
            set
            {
                this.Owner_FKField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 3)]
        public string MD5
        {
            get
            {
                return this.MD5Field;
            }
            set
            {
                this.MD5Field = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 4)]
        public Site[] Sites
        {
            get
            {
                return this.SitesField;
            }
            set
            {
                this.SitesField = value;
            }
        }

        [DataMember(EmitDefaultValue = false, Order = 5)]
        public User Owner
        {
            get
            {
                return this.OwnerField;
            }
            set
            {
                this.OwnerField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Name = "SiteState", Namespace = "http://tempuri.org/")]
    public enum SiteState : int
    {

        [EnumMember()]
        Working = 0,

        [EnumMember()]
        Reported = 1,

        [EnumMember()]
        Broken = 2,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "OnlineVideos.OnlineVideosWebservice.OnlineVideosServiceSoap")]
    public interface OnlineVideosServiceSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/RegisterEmail", ReplyAction = "*")]
        RegisterEmailResponse RegisterEmail(RegisterEmailRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/RegisterEmail", ReplyAction = "*")]
        System.Threading.Tasks.Task<RegisterEmailResponse> RegisterEmailAsync(RegisterEmailRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SubmitSite", ReplyAction = "*")]
        SubmitSiteResponse SubmitSite(SubmitSiteRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SubmitSite", ReplyAction = "*")]
        System.Threading.Tasks.Task<SubmitSiteResponse> SubmitSiteAsync(SubmitSiteRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SubmitDll", ReplyAction = "*")]
        SubmitDllResponse SubmitDll(SubmitDllRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SubmitDll", ReplyAction = "*")]
        System.Threading.Tasks.Task<SubmitDllResponse> SubmitDllAsync(SubmitDllRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SubmitReport", ReplyAction = "*")]
        SubmitReportResponse SubmitReport(SubmitReportRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SubmitReport", ReplyAction = "*")]
        System.Threading.Tasks.Task<SubmitReportResponse> SubmitReportAsync(SubmitReportRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname siteName aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetReports", ReplyAction = "*")]
        GetReportsResponse GetReports(GetReportsRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetReports", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetReportsResponse> GetReportsAsync(GetReportsRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname GetSitesOverviewResult aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSitesOverview", ReplyAction = "*")]
        GetSitesOverviewResponse GetSitesOverview(GetSitesOverviewRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSitesOverview", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetSitesOverviewResponse> GetSitesOverviewAsync(GetSitesOverviewRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname GetDllsOverviewResult aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetDllsOverview", ReplyAction = "*")]
        GetDllsOverviewResponse GetDllsOverview(GetDllsOverviewRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetDllsOverview", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetDllsOverviewResponse> GetDllsOverviewAsync(GetDllsOverviewRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetDllOwner", ReplyAction = "*")]
        GetDllOwnerResponse GetDllOwner(GetDllOwnerRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetDllOwner", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetDllOwnerResponse> GetDllOwnerAsync(GetDllOwnerRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname siteName aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteXml", ReplyAction = "*")]
        GetSiteXmlResponse GetSiteXml(GetSiteXmlRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteXml", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetSiteXmlResponse> GetSiteXmlAsync(GetSiteXmlRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname siteName aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteIcon", ReplyAction = "*")]
        GetSiteIconResponse GetSiteIcon(GetSiteIconRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteIcon", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetSiteIconResponse> GetSiteIconAsync(GetSiteIconRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname siteName aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteIconIfChanged", ReplyAction = "*")]
        GetSiteIconIfChangedResponse GetSiteIconIfChanged(GetSiteIconIfChangedRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteIconIfChanged", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetSiteIconIfChangedResponse> GetSiteIconIfChangedAsync(GetSiteIconIfChangedRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname siteName aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteBanner", ReplyAction = "*")]
        GetSiteBannerResponse GetSiteBanner(GetSiteBannerRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteBanner", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetSiteBannerResponse> GetSiteBannerAsync(GetSiteBannerRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname siteName aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteBannerIfChanged", ReplyAction = "*")]
        GetSiteBannerIfChangedResponse GetSiteBannerIfChanged(GetSiteBannerIfChangedRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSiteBannerIfChanged", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetSiteBannerIfChangedResponse> GetSiteBannerIfChangedAsync(GetSiteBannerIfChangedRequest request);

        // CODEGEN: Ein Nachrichtenvertrag wird generiert, da der Elementname name aus dem Namespace http://tempuri.org/ nicht als "nillable" markiert ist.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetDll", ReplyAction = "*")]
        GetDllResponse GetDll(GetDllRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetDll", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetDllResponse> GetDllAsync(GetDllRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterEmailRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterEmail", Namespace = "http://tempuri.org/", Order = 0)]
        public RegisterEmailRequestBody Body;

        public RegisterEmailRequest()
        {
        }

        public RegisterEmailRequest(RegisterEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class RegisterEmailRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string email;

        public RegisterEmailRequestBody()
        {
        }

        public RegisterEmailRequestBody(string email)
        {
            this.email = email;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterEmailResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterEmailResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public RegisterEmailResponseBody Body;

        public RegisterEmailResponse()
        {
        }

        public RegisterEmailResponse(RegisterEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class RegisterEmailResponseBody
    {

        [DataMember(Order = 0)]
        public bool RegisterEmailResult;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string infoMessage;

        public RegisterEmailResponseBody()
        {
        }

        public RegisterEmailResponseBody(bool RegisterEmailResult, string infoMessage)
        {
            this.RegisterEmailResult = RegisterEmailResult;
            this.infoMessage = infoMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SubmitSiteRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitSite", Namespace = "http://tempuri.org/", Order = 0)]
        public SubmitSiteRequestBody Body;

        public SubmitSiteRequest()
        {
        }

        public SubmitSiteRequest(SubmitSiteRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class SubmitSiteRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string email;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string password;

        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string siteXml;

        [DataMember(EmitDefaultValue = false, Order = 3)]
        public byte[] icon;

        [DataMember(EmitDefaultValue = false, Order = 4)]
        public byte[] banner;

        [DataMember(EmitDefaultValue = false, Order = 5)]
        public string requiredDll;

        public SubmitSiteRequestBody()
        {
        }

        public SubmitSiteRequestBody(string email, string password, string siteXml, byte[] icon, byte[] banner, string requiredDll)
        {
            this.email = email;
            this.password = password;
            this.siteXml = siteXml;
            this.icon = icon;
            this.banner = banner;
            this.requiredDll = requiredDll;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SubmitSiteResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitSiteResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public SubmitSiteResponseBody Body;

        public SubmitSiteResponse()
        {
        }

        public SubmitSiteResponse(SubmitSiteResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class SubmitSiteResponseBody
    {

        [DataMember(Order = 0)]
        public bool SubmitSiteResult;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string infoMessage;

        public SubmitSiteResponseBody()
        {
        }

        public SubmitSiteResponseBody(bool SubmitSiteResult, string infoMessage)
        {
            this.SubmitSiteResult = SubmitSiteResult;
            this.infoMessage = infoMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SubmitDllRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitDll", Namespace = "http://tempuri.org/", Order = 0)]
        public SubmitDllRequestBody Body;

        public SubmitDllRequest()
        {
        }

        public SubmitDllRequest(SubmitDllRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class SubmitDllRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string email;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string password;

        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string name;

        [DataMember(EmitDefaultValue = false, Order = 3)]
        public byte[] data;

        public SubmitDllRequestBody()
        {
        }

        public SubmitDllRequestBody(string email, string password, string name, byte[] data)
        {
            this.email = email;
            this.password = password;
            this.name = name;
            this.data = data;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SubmitDllResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitDllResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public SubmitDllResponseBody Body;

        public SubmitDllResponse()
        {
        }

        public SubmitDllResponse(SubmitDllResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class SubmitDllResponseBody
    {

        [DataMember(Order = 0)]
        public bool SubmitDllResult;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string infoMessage;

        public SubmitDllResponseBody()
        {
        }

        public SubmitDllResponseBody(bool SubmitDllResult, string infoMessage)
        {
            this.SubmitDllResult = SubmitDllResult;
            this.infoMessage = infoMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SubmitReportRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitReport", Namespace = "http://tempuri.org/", Order = 0)]
        public SubmitReportRequestBody Body;

        public SubmitReportRequest()
        {
        }

        public SubmitReportRequest(SubmitReportRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class SubmitReportRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string siteName;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string message;

        [DataMember(Order = 2)]
        public ReportType type;

        public SubmitReportRequestBody()
        {
        }

        public SubmitReportRequestBody(string siteName, string message, ReportType type)
        {
            this.siteName = siteName;
            this.message = message;
            this.type = type;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SubmitReportResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitReportResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public SubmitReportResponseBody Body;

        public SubmitReportResponse()
        {
        }

        public SubmitReportResponse(SubmitReportResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class SubmitReportResponseBody
    {

        [DataMember(Order = 0)]
        public bool SubmitReportResult;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string infoMessage;

        public SubmitReportResponseBody()
        {
        }

        public SubmitReportResponseBody(bool SubmitReportResult, string infoMessage)
        {
            this.SubmitReportResult = SubmitReportResult;
            this.infoMessage = infoMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetReportsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetReports", Namespace = "http://tempuri.org/", Order = 0)]
        public GetReportsRequestBody Body;

        public GetReportsRequest()
        {
        }

        public GetReportsRequest(GetReportsRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetReportsRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string siteName;

        public GetReportsRequestBody()
        {
        }

        public GetReportsRequestBody(string siteName)
        {
            this.siteName = siteName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetReportsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetReportsResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetReportsResponseBody Body;

        public GetReportsResponse()
        {
        }

        public GetReportsResponse(GetReportsResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetReportsResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public Report[] GetReportsResult;

        public GetReportsResponseBody()
        {
        }

        public GetReportsResponseBody(Report[] GetReportsResult)
        {
            this.GetReportsResult = GetReportsResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSitesOverviewRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSitesOverview", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSitesOverviewRequestBody Body;

        public GetSitesOverviewRequest()
        {
        }

        public GetSitesOverviewRequest(GetSitesOverviewRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class GetSitesOverviewRequestBody
    {

        public GetSitesOverviewRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSitesOverviewResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSitesOverviewResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSitesOverviewResponseBody Body;

        public GetSitesOverviewResponse()
        {
        }

        public GetSitesOverviewResponse(GetSitesOverviewResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSitesOverviewResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public Site[] GetSitesOverviewResult;

        public GetSitesOverviewResponseBody()
        {
        }

        public GetSitesOverviewResponseBody(Site[] GetSitesOverviewResult)
        {
            this.GetSitesOverviewResult = GetSitesOverviewResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetDllsOverviewRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDllsOverview", Namespace = "http://tempuri.org/", Order = 0)]
        public GetDllsOverviewRequestBody Body;

        public GetDllsOverviewRequest()
        {
        }

        public GetDllsOverviewRequest(GetDllsOverviewRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class GetDllsOverviewRequestBody
    {

        public GetDllsOverviewRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetDllsOverviewResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDllsOverviewResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetDllsOverviewResponseBody Body;

        public GetDllsOverviewResponse()
        {
        }

        public GetDllsOverviewResponse(GetDllsOverviewResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetDllsOverviewResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public Dll[] GetDllsOverviewResult;

        public GetDllsOverviewResponseBody()
        {
        }

        public GetDllsOverviewResponseBody(Dll[] GetDllsOverviewResult)
        {
            this.GetDllsOverviewResult = GetDllsOverviewResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetDllOwnerRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDllOwner", Namespace = "http://tempuri.org/", Order = 0)]
        public GetDllOwnerRequestBody Body;

        public GetDllOwnerRequest()
        {
        }

        public GetDllOwnerRequest(GetDllOwnerRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetDllOwnerRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string dllName;

        public GetDllOwnerRequestBody()
        {
        }

        public GetDllOwnerRequestBody(string dllName)
        {
            this.dllName = dllName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetDllOwnerResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDllOwnerResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetDllOwnerResponseBody Body;

        public GetDllOwnerResponse()
        {
        }

        public GetDllOwnerResponse(GetDllOwnerResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetDllOwnerResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string GetDllOwnerResult;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string MD5;

        public GetDllOwnerResponseBody()
        {
        }

        public GetDllOwnerResponseBody(string GetDllOwnerResult, string MD5)
        {
            this.GetDllOwnerResult = GetDllOwnerResult;
            this.MD5 = MD5;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteXmlRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteXml", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteXmlRequestBody Body;

        public GetSiteXmlRequest()
        {
        }

        public GetSiteXmlRequest(GetSiteXmlRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteXmlRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string siteName;

        public GetSiteXmlRequestBody()
        {
        }

        public GetSiteXmlRequestBody(string siteName)
        {
            this.siteName = siteName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteXmlResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteXmlResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteXmlResponseBody Body;

        public GetSiteXmlResponse()
        {
        }

        public GetSiteXmlResponse(GetSiteXmlResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteXmlResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string GetSiteXmlResult;

        public GetSiteXmlResponseBody()
        {
        }

        public GetSiteXmlResponseBody(string GetSiteXmlResult)
        {
            this.GetSiteXmlResult = GetSiteXmlResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteIconRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteIcon", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteIconRequestBody Body;

        public GetSiteIconRequest()
        {
        }

        public GetSiteIconRequest(GetSiteIconRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteIconRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string siteName;

        public GetSiteIconRequestBody()
        {
        }

        public GetSiteIconRequestBody(string siteName)
        {
            this.siteName = siteName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteIconResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteIconResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteIconResponseBody Body;

        public GetSiteIconResponse()
        {
        }

        public GetSiteIconResponse(GetSiteIconResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteIconResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public byte[] GetSiteIconResult;

        public GetSiteIconResponseBody()
        {
        }

        public GetSiteIconResponseBody(byte[] GetSiteIconResult)
        {
            this.GetSiteIconResult = GetSiteIconResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteIconIfChangedRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteIconIfChanged", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteIconIfChangedRequestBody Body;

        public GetSiteIconIfChangedRequest()
        {
        }

        public GetSiteIconIfChangedRequest(GetSiteIconIfChangedRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteIconIfChangedRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string siteName;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string md5;

        public GetSiteIconIfChangedRequestBody()
        {
        }

        public GetSiteIconIfChangedRequestBody(string siteName, string md5)
        {
            this.siteName = siteName;
            this.md5 = md5;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteIconIfChangedResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteIconIfChangedResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteIconIfChangedResponseBody Body;

        public GetSiteIconIfChangedResponse()
        {
        }

        public GetSiteIconIfChangedResponse(GetSiteIconIfChangedResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteIconIfChangedResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public byte[] GetSiteIconIfChangedResult;

        public GetSiteIconIfChangedResponseBody()
        {
        }

        public GetSiteIconIfChangedResponseBody(byte[] GetSiteIconIfChangedResult)
        {
            this.GetSiteIconIfChangedResult = GetSiteIconIfChangedResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteBannerRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteBanner", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteBannerRequestBody Body;

        public GetSiteBannerRequest()
        {
        }

        public GetSiteBannerRequest(GetSiteBannerRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteBannerRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string siteName;

        public GetSiteBannerRequestBody()
        {
        }

        public GetSiteBannerRequestBody(string siteName)
        {
            this.siteName = siteName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteBannerResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteBannerResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteBannerResponseBody Body;

        public GetSiteBannerResponse()
        {
        }

        public GetSiteBannerResponse(GetSiteBannerResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteBannerResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public byte[] GetSiteBannerResult;

        public GetSiteBannerResponseBody()
        {
        }

        public GetSiteBannerResponseBody(byte[] GetSiteBannerResult)
        {
            this.GetSiteBannerResult = GetSiteBannerResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteBannerIfChangedRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteBannerIfChanged", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteBannerIfChangedRequestBody Body;

        public GetSiteBannerIfChangedRequest()
        {
        }

        public GetSiteBannerIfChangedRequest(GetSiteBannerIfChangedRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteBannerIfChangedRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string siteName;

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string md5;

        public GetSiteBannerIfChangedRequestBody()
        {
        }

        public GetSiteBannerIfChangedRequestBody(string siteName, string md5)
        {
            this.siteName = siteName;
            this.md5 = md5;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSiteBannerIfChangedResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSiteBannerIfChangedResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetSiteBannerIfChangedResponseBody Body;

        public GetSiteBannerIfChangedResponse()
        {
        }

        public GetSiteBannerIfChangedResponse(GetSiteBannerIfChangedResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetSiteBannerIfChangedResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public byte[] GetSiteBannerIfChangedResult;

        public GetSiteBannerIfChangedResponseBody()
        {
        }

        public GetSiteBannerIfChangedResponseBody(byte[] GetSiteBannerIfChangedResult)
        {
            this.GetSiteBannerIfChangedResult = GetSiteBannerIfChangedResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetDllRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDll", Namespace = "http://tempuri.org/", Order = 0)]
        public GetDllRequestBody Body;

        public GetDllRequest()
        {
        }

        public GetDllRequest(GetDllRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetDllRequestBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public string name;

        public GetDllRequestBody()
        {
        }

        public GetDllRequestBody(string name)
        {
            this.name = name;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetDllResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDllResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public GetDllResponseBody Body;

        public GetDllResponse()
        {
        }

        public GetDllResponse(GetDllResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace = "http://tempuri.org/")]
    public partial class GetDllResponseBody
    {

        [DataMember(EmitDefaultValue = false, Order = 0)]
        public byte[] GetDllResult;

        public GetDllResponseBody()
        {
        }

        public GetDllResponseBody(byte[] GetDllResult)
        {
            this.GetDllResult = GetDllResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface OnlineVideosServiceSoapChannel : OnlineVideosServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class OnlineVideosServiceSoapClient : System.ServiceModel.ClientBase<OnlineVideosServiceSoap>, OnlineVideosServiceSoap
    {

        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public OnlineVideosServiceSoapClient(EndpointConfiguration endpointConfiguration) :
                base(OnlineVideosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), OnlineVideosServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OnlineVideosServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(OnlineVideosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OnlineVideosServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(OnlineVideosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OnlineVideosServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RegisterEmailResponse OnlineVideosServiceSoap.RegisterEmail(RegisterEmailRequest request)
        {
            return base.Channel.RegisterEmail(request);
        }

        public bool RegisterEmail(string email, out string infoMessage)
        {
            RegisterEmailRequest inValue = new RegisterEmailRequest();
            inValue.Body = new RegisterEmailRequestBody();
            inValue.Body.email = email;
            RegisterEmailResponse retVal = ((OnlineVideosServiceSoap)(this)).RegisterEmail(inValue);
            infoMessage = retVal.Body.infoMessage;
            return retVal.Body.RegisterEmailResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RegisterEmailResponse> OnlineVideosServiceSoap.RegisterEmailAsync(RegisterEmailRequest request)
        {
            return base.Channel.RegisterEmailAsync(request);
        }

        public System.Threading.Tasks.Task<RegisterEmailResponse> RegisterEmailAsync(string email)
        {
            RegisterEmailRequest inValue = new RegisterEmailRequest();
            inValue.Body = new RegisterEmailRequestBody();
            inValue.Body.email = email;
            return ((OnlineVideosServiceSoap)(this)).RegisterEmailAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubmitSiteResponse OnlineVideosServiceSoap.SubmitSite(SubmitSiteRequest request)
        {
            return base.Channel.SubmitSite(request);
        }

        public bool SubmitSite(string email, string password, string siteXml, byte[] icon, byte[] banner, string requiredDll, out string infoMessage)
        {
            SubmitSiteRequest inValue = new SubmitSiteRequest();
            inValue.Body = new SubmitSiteRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.siteXml = siteXml;
            inValue.Body.icon = icon;
            inValue.Body.banner = banner;
            inValue.Body.requiredDll = requiredDll;
            SubmitSiteResponse retVal = ((OnlineVideosServiceSoap)(this)).SubmitSite(inValue);
            infoMessage = retVal.Body.infoMessage;
            return retVal.Body.SubmitSiteResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubmitSiteResponse> OnlineVideosServiceSoap.SubmitSiteAsync(SubmitSiteRequest request)
        {
            return base.Channel.SubmitSiteAsync(request);
        }

        public System.Threading.Tasks.Task<SubmitSiteResponse> SubmitSiteAsync(string email, string password, string siteXml, byte[] icon, byte[] banner, string requiredDll)
        {
            SubmitSiteRequest inValue = new SubmitSiteRequest();
            inValue.Body = new SubmitSiteRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.siteXml = siteXml;
            inValue.Body.icon = icon;
            inValue.Body.banner = banner;
            inValue.Body.requiredDll = requiredDll;
            return ((OnlineVideosServiceSoap)(this)).SubmitSiteAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubmitDllResponse OnlineVideosServiceSoap.SubmitDll(SubmitDllRequest request)
        {
            return base.Channel.SubmitDll(request);
        }

        public bool SubmitDll(string email, string password, string name, byte[] data, out string infoMessage)
        {
            SubmitDllRequest inValue = new SubmitDllRequest();
            inValue.Body = new SubmitDllRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.name = name;
            inValue.Body.data = data;
            SubmitDllResponse retVal = ((OnlineVideosServiceSoap)(this)).SubmitDll(inValue);
            infoMessage = retVal.Body.infoMessage;
            return retVal.Body.SubmitDllResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubmitDllResponse> OnlineVideosServiceSoap.SubmitDllAsync(SubmitDllRequest request)
        {
            return base.Channel.SubmitDllAsync(request);
        }

        public System.Threading.Tasks.Task<SubmitDllResponse> SubmitDllAsync(string email, string password, string name, byte[] data)
        {
            SubmitDllRequest inValue = new SubmitDllRequest();
            inValue.Body = new SubmitDllRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.name = name;
            inValue.Body.data = data;
            return ((OnlineVideosServiceSoap)(this)).SubmitDllAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SubmitReportResponse OnlineVideosServiceSoap.SubmitReport(SubmitReportRequest request)
        {
            return base.Channel.SubmitReport(request);
        }

        public bool SubmitReport(string siteName, string message, ReportType type, out string infoMessage)
        {
            SubmitReportRequest inValue = new SubmitReportRequest();
            inValue.Body = new SubmitReportRequestBody();
            inValue.Body.siteName = siteName;
            inValue.Body.message = message;
            inValue.Body.type = type;
            SubmitReportResponse retVal = ((OnlineVideosServiceSoap)(this)).SubmitReport(inValue);
            infoMessage = retVal.Body.infoMessage;
            return retVal.Body.SubmitReportResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SubmitReportResponse> OnlineVideosServiceSoap.SubmitReportAsync(SubmitReportRequest request)
        {
            return base.Channel.SubmitReportAsync(request);
        }

        public System.Threading.Tasks.Task<SubmitReportResponse> SubmitReportAsync(string siteName, string message, ReportType type)
        {
            SubmitReportRequest inValue = new SubmitReportRequest();
            inValue.Body = new SubmitReportRequestBody();
            inValue.Body.siteName = siteName;
            inValue.Body.message = message;
            inValue.Body.type = type;
            return ((OnlineVideosServiceSoap)(this)).SubmitReportAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetReportsResponse OnlineVideosServiceSoap.GetReports(GetReportsRequest request)
        {
            return base.Channel.GetReports(request);
        }

        public Report[] GetReports(string siteName)
        {
            GetReportsRequest inValue = new GetReportsRequest();
            inValue.Body = new GetReportsRequestBody();
            inValue.Body.siteName = siteName;
            GetReportsResponse retVal = ((OnlineVideosServiceSoap)(this)).GetReports(inValue);
            return retVal.Body.GetReportsResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetReportsResponse> OnlineVideosServiceSoap.GetReportsAsync(GetReportsRequest request)
        {
            return base.Channel.GetReportsAsync(request);
        }

        public System.Threading.Tasks.Task<GetReportsResponse> GetReportsAsync(string siteName)
        {
            GetReportsRequest inValue = new GetReportsRequest();
            inValue.Body = new GetReportsRequestBody();
            inValue.Body.siteName = siteName;
            return ((OnlineVideosServiceSoap)(this)).GetReportsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetSitesOverviewResponse OnlineVideosServiceSoap.GetSitesOverview(GetSitesOverviewRequest request)
        {
            return base.Channel.GetSitesOverview(request);
        }

        public Site[] GetSitesOverview()
        {
            GetSitesOverviewRequest inValue = new GetSitesOverviewRequest();
            inValue.Body = new GetSitesOverviewRequestBody();
            GetSitesOverviewResponse retVal = ((OnlineVideosServiceSoap)(this)).GetSitesOverview(inValue);
            return retVal.Body.GetSitesOverviewResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetSitesOverviewResponse> OnlineVideosServiceSoap.GetSitesOverviewAsync(GetSitesOverviewRequest request)
        {
            return base.Channel.GetSitesOverviewAsync(request);
        }

        public System.Threading.Tasks.Task<GetSitesOverviewResponse> GetSitesOverviewAsync()
        {
            GetSitesOverviewRequest inValue = new GetSitesOverviewRequest();
            inValue.Body = new GetSitesOverviewRequestBody();
            return ((OnlineVideosServiceSoap)(this)).GetSitesOverviewAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDllsOverviewResponse OnlineVideosServiceSoap.GetDllsOverview(GetDllsOverviewRequest request)
        {
            return base.Channel.GetDllsOverview(request);
        }

        public Dll[] GetDllsOverview()
        {
            GetDllsOverviewRequest inValue = new GetDllsOverviewRequest();
            inValue.Body = new GetDllsOverviewRequestBody();
            GetDllsOverviewResponse retVal = ((OnlineVideosServiceSoap)(this)).GetDllsOverview(inValue);
            return retVal.Body.GetDllsOverviewResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetDllsOverviewResponse> OnlineVideosServiceSoap.GetDllsOverviewAsync(GetDllsOverviewRequest request)
        {
            return base.Channel.GetDllsOverviewAsync(request);
        }

        public System.Threading.Tasks.Task<GetDllsOverviewResponse> GetDllsOverviewAsync()
        {
            GetDllsOverviewRequest inValue = new GetDllsOverviewRequest();
            inValue.Body = new GetDllsOverviewRequestBody();
            return ((OnlineVideosServiceSoap)(this)).GetDllsOverviewAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDllOwnerResponse OnlineVideosServiceSoap.GetDllOwner(GetDllOwnerRequest request)
        {
            return base.Channel.GetDllOwner(request);
        }

        public string GetDllOwner(string dllName, out string MD5)
        {
            GetDllOwnerRequest inValue = new GetDllOwnerRequest();
            inValue.Body = new GetDllOwnerRequestBody();
            inValue.Body.dllName = dllName;
            GetDllOwnerResponse retVal = ((OnlineVideosServiceSoap)(this)).GetDllOwner(inValue);
            MD5 = retVal.Body.MD5;
            return retVal.Body.GetDllOwnerResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetDllOwnerResponse> OnlineVideosServiceSoap.GetDllOwnerAsync(GetDllOwnerRequest request)
        {
            return base.Channel.GetDllOwnerAsync(request);
        }

        public System.Threading.Tasks.Task<GetDllOwnerResponse> GetDllOwnerAsync(string dllName)
        {
            GetDllOwnerRequest inValue = new GetDllOwnerRequest();
            inValue.Body = new GetDllOwnerRequestBody();
            inValue.Body.dllName = dllName;
            return ((OnlineVideosServiceSoap)(this)).GetDllOwnerAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetSiteXmlResponse OnlineVideosServiceSoap.GetSiteXml(GetSiteXmlRequest request)
        {
            return base.Channel.GetSiteXml(request);
        }

        public string GetSiteXml(string siteName)
        {
            GetSiteXmlRequest inValue = new GetSiteXmlRequest();
            inValue.Body = new GetSiteXmlRequestBody();
            inValue.Body.siteName = siteName;
            GetSiteXmlResponse retVal = ((OnlineVideosServiceSoap)(this)).GetSiteXml(inValue);
            return retVal.Body.GetSiteXmlResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetSiteXmlResponse> OnlineVideosServiceSoap.GetSiteXmlAsync(GetSiteXmlRequest request)
        {
            return base.Channel.GetSiteXmlAsync(request);
        }

        public System.Threading.Tasks.Task<GetSiteXmlResponse> GetSiteXmlAsync(string siteName)
        {
            GetSiteXmlRequest inValue = new GetSiteXmlRequest();
            inValue.Body = new GetSiteXmlRequestBody();
            inValue.Body.siteName = siteName;
            return ((OnlineVideosServiceSoap)(this)).GetSiteXmlAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetSiteIconResponse OnlineVideosServiceSoap.GetSiteIcon(GetSiteIconRequest request)
        {
            return base.Channel.GetSiteIcon(request);
        }

        public byte[] GetSiteIcon(string siteName)
        {
            GetSiteIconRequest inValue = new GetSiteIconRequest();
            inValue.Body = new GetSiteIconRequestBody();
            inValue.Body.siteName = siteName;
            GetSiteIconResponse retVal = ((OnlineVideosServiceSoap)(this)).GetSiteIcon(inValue);
            return retVal.Body.GetSiteIconResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetSiteIconResponse> OnlineVideosServiceSoap.GetSiteIconAsync(GetSiteIconRequest request)
        {
            return base.Channel.GetSiteIconAsync(request);
        }

        public System.Threading.Tasks.Task<GetSiteIconResponse> GetSiteIconAsync(string siteName)
        {
            GetSiteIconRequest inValue = new GetSiteIconRequest();
            inValue.Body = new GetSiteIconRequestBody();
            inValue.Body.siteName = siteName;
            return ((OnlineVideosServiceSoap)(this)).GetSiteIconAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetSiteIconIfChangedResponse OnlineVideosServiceSoap.GetSiteIconIfChanged(GetSiteIconIfChangedRequest request)
        {
            return base.Channel.GetSiteIconIfChanged(request);
        }

        public byte[] GetSiteIconIfChanged(string siteName, string md5)
        {
            GetSiteIconIfChangedRequest inValue = new GetSiteIconIfChangedRequest();
            inValue.Body = new GetSiteIconIfChangedRequestBody();
            inValue.Body.siteName = siteName;
            inValue.Body.md5 = md5;
            GetSiteIconIfChangedResponse retVal = ((OnlineVideosServiceSoap)(this)).GetSiteIconIfChanged(inValue);
            return retVal.Body.GetSiteIconIfChangedResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetSiteIconIfChangedResponse> OnlineVideosServiceSoap.GetSiteIconIfChangedAsync(GetSiteIconIfChangedRequest request)
        {
            return base.Channel.GetSiteIconIfChangedAsync(request);
        }

        public System.Threading.Tasks.Task<GetSiteIconIfChangedResponse> GetSiteIconIfChangedAsync(string siteName, string md5)
        {
            GetSiteIconIfChangedRequest inValue = new GetSiteIconIfChangedRequest();
            inValue.Body = new GetSiteIconIfChangedRequestBody();
            inValue.Body.siteName = siteName;
            inValue.Body.md5 = md5;
            return ((OnlineVideosServiceSoap)(this)).GetSiteIconIfChangedAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetSiteBannerResponse OnlineVideosServiceSoap.GetSiteBanner(GetSiteBannerRequest request)
        {
            return base.Channel.GetSiteBanner(request);
        }

        public byte[] GetSiteBanner(string siteName)
        {
            GetSiteBannerRequest inValue = new GetSiteBannerRequest();
            inValue.Body = new GetSiteBannerRequestBody();
            inValue.Body.siteName = siteName;
            GetSiteBannerResponse retVal = ((OnlineVideosServiceSoap)(this)).GetSiteBanner(inValue);
            return retVal.Body.GetSiteBannerResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetSiteBannerResponse> OnlineVideosServiceSoap.GetSiteBannerAsync(GetSiteBannerRequest request)
        {
            return base.Channel.GetSiteBannerAsync(request);
        }

        public System.Threading.Tasks.Task<GetSiteBannerResponse> GetSiteBannerAsync(string siteName)
        {
            GetSiteBannerRequest inValue = new GetSiteBannerRequest();
            inValue.Body = new GetSiteBannerRequestBody();
            inValue.Body.siteName = siteName;
            return ((OnlineVideosServiceSoap)(this)).GetSiteBannerAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetSiteBannerIfChangedResponse OnlineVideosServiceSoap.GetSiteBannerIfChanged(GetSiteBannerIfChangedRequest request)
        {
            return base.Channel.GetSiteBannerIfChanged(request);
        }

        public byte[] GetSiteBannerIfChanged(string siteName, string md5)
        {
            GetSiteBannerIfChangedRequest inValue = new GetSiteBannerIfChangedRequest();
            inValue.Body = new GetSiteBannerIfChangedRequestBody();
            inValue.Body.siteName = siteName;
            inValue.Body.md5 = md5;
            GetSiteBannerIfChangedResponse retVal = ((OnlineVideosServiceSoap)(this)).GetSiteBannerIfChanged(inValue);
            return retVal.Body.GetSiteBannerIfChangedResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetSiteBannerIfChangedResponse> OnlineVideosServiceSoap.GetSiteBannerIfChangedAsync(GetSiteBannerIfChangedRequest request)
        {
            return base.Channel.GetSiteBannerIfChangedAsync(request);
        }

        public System.Threading.Tasks.Task<GetSiteBannerIfChangedResponse> GetSiteBannerIfChangedAsync(string siteName, string md5)
        {
            GetSiteBannerIfChangedRequest inValue = new GetSiteBannerIfChangedRequest();
            inValue.Body = new GetSiteBannerIfChangedRequestBody();
            inValue.Body.siteName = siteName;
            inValue.Body.md5 = md5;
            return ((OnlineVideosServiceSoap)(this)).GetSiteBannerIfChangedAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDllResponse OnlineVideosServiceSoap.GetDll(GetDllRequest request)
        {
            return base.Channel.GetDll(request);
        }

        public byte[] GetDll(string name)
        {
            GetDllRequest inValue = new GetDllRequest();
            inValue.Body = new GetDllRequestBody();
            inValue.Body.name = name;
            GetDllResponse retVal = ((OnlineVideosServiceSoap)(this)).GetDll(inValue);
            return retVal.Body.GetDllResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetDllResponse> OnlineVideosServiceSoap.GetDllAsync(GetDllRequest request)
        {
            return base.Channel.GetDllAsync(request);
        }

        public System.Threading.Tasks.Task<GetDllResponse> GetDllAsync(string name)
        {
            GetDllRequest inValue = new GetDllRequest();
            inValue.Body = new GetDllRequestBody();
            inValue.Body.name = name;
            return ((OnlineVideosServiceSoap)(this)).GetDllAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OnlineVideosServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OnlineVideosServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OnlineVideosServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://onlinevideos.nocrosshair.de/OnlineVideos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OnlineVideosServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://onlinevideos.nocrosshair.de/OnlineVideos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            OnlineVideosServiceSoap,

            OnlineVideosServiceSoap12,
        }
    }
}
