//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVideos.Sites.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineVideos.Sites.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function __gotoClickEpisode(e) {
        ///    var xpath = &quot;//span[text()=&apos;&quot; + e + &quot;&apos;]&quot;;
        ///    var matchingElement = document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
        ///}
        ///
        ///function __slugify(a) {
        ///    var b, c, d = &quot;àáäâèéëêìíïîòóöôùúüûñç·/_,:;&quot;, e = &quot;aaaaeeeeiiiioooouuuunc------&quot;;
        ///    for (a = a.replace(/^\s+|\s+$/g, &quot;&quot;), a = a.toLowerCase(), b = 0, c = d.length; c &gt; b; b++)
        ///        a = a.replace(new RegExp(d.charAt(b), &quot;g&quot;), e.charAt(b));
        ///    return a = a.repla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HboNordicJs {
            get {
                return ResourceManager.GetString("HboNordicJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function myLogin(u, p) {
        ///    $(&apos;#LoginForm_email&apos;).val(u);
        ///    $(&apos;#LoginForm_password&apos;).val(p);
        ///    $(&apos;#login-btn&apos;).click();
        ///}
        ///
        ///var __url = &quot;dummy&quot;;
        ///
        ///function myPlay() {
        ///    var __m = $(&apos;a[href$=&quot;&apos; + __url + &apos;&quot;]&apos;).first();
        ///    if (__m.length &gt; 0) {
        ///        __m.click();
        ///    } else {
        ///        setTimeout(&quot;myPlay()&quot;, 250);
        ///    }
        ///};.
        /// </summary>
        internal static string ViaplayPlayMovieJs {
            get {
                return ResourceManager.GetString("ViaplayPlayMovieJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var steps = [-10000000, -7200, -3600, -1800, -900, -600, -300, -180, -60, -30, -15, 0, 15, 30, 60, 180, 300, 600, 900, 1800, 3600, 7200, 10000000];
        ///var stepNames = [&apos;Start&apos;, &apos;-2h&apos;, &apos;-1h&apos;, &apos;-30m&apos;, &apos;-15m&apos;, &apos;-10m&apos;, &apos;-5m&apos;, &apos;-3m&apos;, &apos;-1m&apos;, &apos;-30s&apos;, &apos;-15s&apos;, &apos; &apos;, &apos;+15s&apos;, &apos;+30s&apos;, &apos;+1m&apos;, &apos;+3m&apos;, &apos;+5m&apos;, &apos;+10m&apos;, &apos;+15m&apos;, &apos;+30m&apos;, &apos;+1h&apos;, &apos;+2h&apos;, &apos;End&apos;];
        ///var skipIndex = 11;
        ///var minIndex = 0;
        ///var maxIndex = steps.length - 1;
        ///var skipTimeout = 3000;
        ///var skipTimer = null;
        ///
        ///var contentDiv = document.getElementById(&apos;content [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViaplayVideoControlJs {
            get {
                return ResourceManager.GetString("ViaplayVideoControlJs", resourceCulture);
            }
        }
    }
}
