//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVideos.Sites.WebAutomation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineVideos.Sites.WebAutomation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.channel4.com/programmes/4od/catchup.
        /// </summary>
        public static string _4OD_CatchUpUrl {
            get {
                return ResourceManager.GetString("_4OD_CatchUpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.channel4.com/programmes/tags/{CATEGORY}4od/title/brand-list/page-1.
        /// </summary>
        public static string _4OD_CategoryListUrl {
            get {
                return ResourceManager.GetString("_4OD_CategoryListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.channel4.com/programmes/4od/collections/page-1.
        /// </summary>
        public static string _4OD_CollectionListUrl {
            get {
                return ResourceManager.GetString("_4OD_CollectionListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://4id.channel4.com/login.
        /// </summary>
        public static string _4OD_LoginUrl {
            get {
                return ResourceManager.GetString("_4OD_LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.channel4.com.
        /// </summary>
        public static string _4OD_RootUrl {
            get {
                return ResourceManager.GetString("_4OD_RootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.channel4.com/programmes/asset/{VIDEO_ID}.
        /// </summary>
        public static string _4OD_VideoDetailsUrl {
            get {
                return ResourceManager.GetString("_4OD_VideoDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.channel4.com/programmes/{VIDEO_NAME}/4od/player/{VIDEO_ID}.
        /// </summary>
        public static string _4OD_VideoPlayUrl {
            get {
                return ResourceManager.GetString("_4OD_VideoPlayUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com/vod/content/{CATEGORY}/All/content/default/promoPage.do?aToZ.indexCharacter={CHARACTER}&amp;aToZ.viewIndex={PAGE}&amp;aaxmlrequest=true&amp;aazones=content.
        /// </summary>
        public static string SkyGo_CategoryAToZUrl {
            get {
                return ResourceManager.GetString("SkyGo_CategoryAToZUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com/tvlistings-proxy/TvListingsApi/xml/v2/nowNextLater.do?channelIds={CHANNEL_IDS}&amp;siteId=4&amp;accessKey=fdgJRTd345S4fKMER92mddSFJWERJ35285FDdm3412jdRTmsdd.
        /// </summary>
        public static string SkyGo_LiveTvGetNowNextUrl {
            get {
                return ResourceManager.GetString("SkyGo_LiveTvGetNowNextUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com/vod/page/tvListing.do.
        /// </summary>
        public static string SkyGo_LiveTvListingUrl {
            get {
                return ResourceManager.GetString("SkyGo_LiveTvListingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com/vod/content/Home/content/videoId/{VIDEO_ID}____/l/l/content/detachedLiveTv.do.
        /// </summary>
        public static string SkyGo_LiveTvPlayUrl {
            get {
                return ResourceManager.GetString("SkyGo_LiveTvPlayUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://skyid.sky.com/signin/skygo.
        /// </summary>
        public static string SkyGo_LoginUrl {
            get {
                return ResourceManager.GetString("SkyGo_LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com.
        /// </summary>
        public static string SkyGo_RootUrl {
            get {
                return ResourceManager.GetString("SkyGo_RootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com/vod/content/SKYENTERTAINMENT/Browse_by_Genre/A-Z/content/seriesId/{SERIES_ID}/content/default/promoPage.do?aaxmlrequest=true&amp;aazones=content.
        /// </summary>
        public static string SkyGo_SeriesDetailsUrl {
            get {
                return ResourceManager.GetString("SkyGo_SeriesDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com/vod/content/SKYENTERTAINMENT/content/videoId/{VIDEO_ID}/l/l/content/videoActions.do?aaxmlrequest=true&amp;aazones=vdactions.
        /// </summary>
        public static string SkyGo_VideoActionsUrl {
            get {
                return ResourceManager.GetString("SkyGo_VideoActionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com/vod/content/SKYENTERTAINMENT/content/videoId/{VIDEO_ID}/content/1984/videoDetailsPage.do?aaxmlrequest=true&amp;aazones=content.
        /// </summary>
        public static string SkyGo_VideoDetailsUrl {
            get {
                return ResourceManager.GetString("SkyGo_VideoDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.sky.com/vod/content/SKYENTERTAINMENT/content/assetId/{ASSET_ID}/videoId/{VIDEO_ID}/l/l/content/progressivePlay.do.
        /// </summary>
        public static string SkyGo_VideoPlayUrl {
            get {
                return ResourceManager.GetString("SkyGo_VideoPlayUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://epgstatic.sky.com/epgdata/1.0/newchanlogos/75/35/skychb{CHANNEL_ID}.png.
        /// </summary>
        public static string SkyGoLiveTvImageUrl {
            get {
                return ResourceManager.GetString("SkyGoLiveTvImageUrl", resourceCulture);
            }
        }
    }
}
