//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVideos.Sites.WebAutomation.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineVideos.Sites.WebAutomation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.channel4.com/programmes/4od/catchup ähnelt.
        /// </summary>
        public static string _4OD_CatchUpUrl {
            get {
                return ResourceManager.GetString("_4OD_CatchUpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.channel4.com/programmes/tags/{CATEGORY}4od/title/brand-list/page-1 ähnelt.
        /// </summary>
        public static string _4OD_CategoryListUrl {
            get {
                return ResourceManager.GetString("_4OD_CategoryListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.channel4.com/programmes/4od/collections/page-1 ähnelt.
        /// </summary>
        public static string _4OD_CollectionListUrl {
            get {
                return ResourceManager.GetString("_4OD_CollectionListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://4id.channel4.com/login ähnelt.
        /// </summary>
        public static string _4OD_LoginUrl {
            get {
                return ResourceManager.GetString("_4OD_LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.channel4.com ähnelt.
        /// </summary>
        public static string _4OD_RootUrl {
            get {
                return ResourceManager.GetString("_4OD_RootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.channel4.com/programmes/asset/{VIDEO_ID} ähnelt.
        /// </summary>
        public static string _4OD_VideoDetailsUrl {
            get {
                return ResourceManager.GetString("_4OD_VideoDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.channel4.com/programmes/{VIDEO_NAME}/4od/player/{VIDEO_ID} ähnelt.
        /// </summary>
        public static string _4OD_VideoPlayUrl {
            get {
                return ResourceManager.GetString("_4OD_VideoPlayUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.amazon.co.uk/ap/signin?_encoding=UTF8&amp;openid.assoc_handle=gbflex&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&amp;openid.pape.max_auth_age=0&amp;openid.return_to=https%3A%2F%2Fwww.amazon.co.uk%2Fgp%2Fyourstore%2Fhome%3Fie%3DUTF8%26ref_%3Dnav_s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string AmazonLoginUrl {
            get {
                return ResourceManager.GetString("AmazonLoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.amazon.co.uk/Prime-Movie-Genres/b/ref=atv_sn_piv_cl1_mv_gn?_encoding=UTF8&amp;node=3788183031 ähnelt.
        /// </summary>
        public static string AmazonMovieCategoriesUrl {
            get {
                return ResourceManager.GetString("AmazonMovieCategoriesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://ecx.images-amazon.com/images/I/51b8AY8hQBL._SX200_.jpg ähnelt.
        /// </summary>
        public static string AmazonMovieIcon {
            get {
                return ResourceManager.GetString("AmazonMovieIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.amazon.co.uk/gp/product/{VIDEO_ID}?ref_=pda_recs_wdgt_nav_dyn_{VIDEO_ID} ähnelt.
        /// </summary>
        public static string AmazonMovieUrl {
            get {
                return ResourceManager.GetString("AmazonMovieUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.amazon.co.uk/Prime-Movie-Genres/b/ref=atv_sn_piv_cl1_mv_gn?_encoding=UTF8&amp;node=3788183031 ähnelt.
        /// </summary>
        public static string AmazonMovieWatchlistUrl {
            get {
                return ResourceManager.GetString("AmazonMovieWatchlistUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.amazon.co.uk ähnelt.
        /// </summary>
        public static string AmazonRootUrl {
            get {
                return ResourceManager.GetString("AmazonRootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.amazon.co.uk/Prime-TV-Genres/b/ref=atv_sn_piv_cl2_tv_gn?_encoding=UTF8&amp;node=3788187031 ähnelt.
        /// </summary>
        public static string AmazonTVCategoriesUrl {
            get {
                return ResourceManager.GetString("AmazonTVCategoriesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://ecx.images-amazon.com/images/I/51qB6Z-XI3L._SX200_.jpg ähnelt.
        /// </summary>
        public static string AmazonTvIcon {
            get {
                return ResourceManager.GetString("AmazonTvIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.amazon.co.uk/Prime-TV-Genres/b/ref=atv_sn_piv_cl2_tv_gn?_encoding=UTF8&amp;node=3788187031 ähnelt.
        /// </summary>
        public static string AmazonTVWatchlistUrl {
            get {
                return ResourceManager.GetString("AmazonTVWatchlistUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com/vod/content/{CATEGORY}/All/content/default/promoPage.do?aToZ.indexCharacter={CHARACTER}&amp;aToZ.viewIndex={PAGE}&amp;aaxmlrequest=true&amp;aazones=content ähnelt.
        /// </summary>
        public static string SkyGo_CategoryAToZUrl {
            get {
                return ResourceManager.GetString("SkyGo_CategoryAToZUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com/tvlistings-proxy/TvListingsApi/xml/v2/nowNextLater.do?channelIds={CHANNEL_IDS}&amp;siteId=4&amp;accessKey=fdgJRTd345S4fKMER92mddSFJWERJ35285FDdm3412jdRTmsdd ähnelt.
        /// </summary>
        public static string SkyGo_LiveTvGetNowNextUrl {
            get {
                return ResourceManager.GetString("SkyGo_LiveTvGetNowNextUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com/vod/page/tvListing.do ähnelt.
        /// </summary>
        public static string SkyGo_LiveTvListingUrl {
            get {
                return ResourceManager.GetString("SkyGo_LiveTvListingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com/vod/content/Home/content/videoId/{VIDEO_ID}____/l/l/content/detachedLiveTv.do ähnelt.
        /// </summary>
        public static string SkyGo_LiveTvPlayUrl {
            get {
                return ResourceManager.GetString("SkyGo_LiveTvPlayUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://skyid.sky.com/signin/skygo ähnelt.
        /// </summary>
        public static string SkyGo_LoginUrl {
            get {
                return ResourceManager.GetString("SkyGo_LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com ähnelt.
        /// </summary>
        public static string SkyGo_RootUrl {
            get {
                return ResourceManager.GetString("SkyGo_RootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com/vod/content/SKYENTERTAINMENT/Browse_by_Genre/A-Z/content/seriesId/{SERIES_ID}/content/default/promoPage.do?aaxmlrequest=true&amp;aazones=content ähnelt.
        /// </summary>
        public static string SkyGo_SeriesDetailsUrl {
            get {
                return ResourceManager.GetString("SkyGo_SeriesDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com/vod/content/SKYENTERTAINMENT/content/videoId/{VIDEO_ID}/l/l/content/videoActions.do?aaxmlrequest=true&amp;aazones=vdactions ähnelt.
        /// </summary>
        public static string SkyGo_VideoActionsUrl {
            get {
                return ResourceManager.GetString("SkyGo_VideoActionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com/vod/content/SKYENTERTAINMENT/content/videoId/{VIDEO_ID}/content/1984/videoDetailsPage.do?aaxmlrequest=true&amp;aazones=content ähnelt.
        /// </summary>
        public static string SkyGo_VideoDetailsUrl {
            get {
                return ResourceManager.GetString("SkyGo_VideoDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.sky.com/vod/content/SKYENTERTAINMENT/content/assetId/{ASSET_ID}/videoId/{VIDEO_ID}/l/l/content/progressivePlay.do ähnelt.
        /// </summary>
        public static string SkyGo_VideoPlayUrl {
            get {
                return ResourceManager.GetString("SkyGo_VideoPlayUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://epgstatic.sky.com/epgdata/1.0/newchanlogos/75/35/skychb{CHANNEL_ID}.png ähnelt.
        /// </summary>
        public static string SkyGoLiveTvImageUrl {
            get {
                return ResourceManager.GetString("SkyGoLiveTvImageUrl", resourceCulture);
            }
        }
    }
}
